### ISSUE TITLE
Just want to know 

### ISSUE THREAD

**Issue by cybersleuth0** [h4r5h1t/webcopilot#4]
What if we already have subdomains now i want to do rest of the things which is provided by webcopilot something like 

`cat subdomain.txt | webcopilot rest of the flags`

or add new flag for selecting subdomain.txt

**Comment by h4r5h1t** [comment]
The current version of webcopilot doesn't directly support taking subdomain input and skipping the scanning process, I plan to integrate this feature into the next release.

#3

**Comment by tezarock** [comment]
Yes, this will be best addition

**Comment by h4r5h1t** [comment]
Implemented the feature request. More information is in PR #17.
